### ISSUE TITLE
WANDB API KEY is Public

### ISSUE THREAD

**Issue by stefaj** [albertfgu/dotfiles#1]
https://github.com/albertfgu/dotfiles/blob/master/aws/.zshrc

**Comment by albertfgu** [comment]
Thanks for the heads up!
Unfortunately I don't see a way to keep this key somewhere convenient, so I may have to make this repo private unless you have any ideas?

**Comment by stefaj** [comment]
When you 
```wandb login 69d3cXXXXXXXXXXX```
it gets saved to .netrc (only needs to happen once on your machine)

and then gets read whenever you use wandb

So depending on your uses maybe you don't need it as an environment variable
